// CVPR 2026 reading list for the Sustainability Lab (IIT Gandhinagar).
// To edit: change entries below. Schema documented in ../README.md.
window.READING_LIST = {
  venue: "CVPR 2026",
  dates: "June 3–7, 2026",
  location: "Denver, Colorado, USA",
  source: "CVF Open Access — 4,069 accepted papers",
  updated: "2026-06-07",
  intro:
    "Curated from all 4,069 CVPR 2026 accepted papers, grouped by the lab's lines of work. " +
    "Each paper is mapped to the lab project(s) it connects to. Relevance was judged from titles " +
    "(abstracts not yet read) — verify before assigning. Tiers: ★ must-read, ○ adjacent/skim. " +
    "Use the search box to filter by topic, lab project, or student area.",

  workshopPapersNote:
    "At build time (conference week, June 2026) only EarthVision had published its full program — its most lab-relevant papers are listed below. " +
    "Agriculture-Vision, MORSE and MONTI had not yet posted accepted papers; CV4Science uses rolling review, so its invited talks are listed instead. Re-scrape after proceedings appear.",

  // Short glossary so students know what each lab project is.
  labWorks: {
    "SentinelKilnDB": "OBB brick-kiln detection dataset & benchmark, South Asia satellite imagery (2025)",
    "Space-to-Policy": "Scalable brick-kiln detection + automatic compliance monitoring (2025)",
    "JoulesEye": "Energy expenditure + respiration from thermal imagery while exercising (IMWUT 2024)",
    "ApneaEye": "Sensing respiration & sleep apnea from thermal imaging in real-world conditions (ongoing) — needs robust nostril localization in low-res thermal",
    "ThermEval": "Structured benchmark for evaluation of thermal models (2026)",
    "SpiroMask": "Lung-function measurement from consumer-grade masks (2023)",
    "SpiroActive": "Active learning for efficient spirometry data acquisition (2024)",
    "Conformal-NILM": "Distribution-free uncertainty quantification & calibration for energy disaggregation (2025)",
    "NILM-UQ": "\"I do not know\": quantifying uncertainty in NN-based NILM (2022)",
    "NILM-AL": "Benchmarking active learning for NILM (2024)",
    "AIRDELHI": "Fine-grained spatio-temporal PM dataset from Delhi (2023)",
    "DeepGP-AQ": "Deep / scalable Gaussian processes for fine-grained air-quality inference (2022–2023)",
    "AQ-SensorPlacement": "Scalable air-quality sensor placement via gradient-based optimization (AAAI 2026)",
    "VayuChat/VayuBuddy": "LLM chatbots & benchmarks for air-quality data analytics (VayuChat, VayuBuddy, VayuBench, 2024–2025)",
    "DRL-HouseControl": "Optimizing pollutant exposure, energy & thermal comfort via deep RL (2025)",
    "PlantDoc": "Plant-disease detection dataset (2020)",
    "Vastr-GAN": "Text-to-apparel synthesis GAN (2022)"
  },

  // Workshops first — the lab is keen on these.
  workshops: [
    { title: "EarthVision: Large-Scale Computer Vision for Remote Sensing Imagery", when: "Thu, full day",
      url: "https://www.grss-ieee.org/events/earthvision-2026/", tier: "must",
      tags: ["remote-sensing","satellite","SAR","yield"],
      why: "The flagship RS@CVPR venue — directly home turf for SentinelKilnDB, Space-to-Policy, SAR and yield student work. Has a paper track + challenges.",
      papers: [
        { title: "SHRUG-FM: Reliability-Aware Foundation Models for Earth Observation (oral)", why: "Reliability/uncertainty-aware EO foundation model — fuses the lab's remote-sensing and UQ interests." },
        { title: "THOR: A Versatile Foundation Model for Earth Observation Climate & Society Applications", why: "EO foundation model aimed at climate/society tasks — a candidate backbone for kiln/policy pipelines." },
        { title: "Beyond Conditional Diffusion: Physics-Guided Joint Forecasting of Physical Drivers and Multispectral Satellite Data", why: "Physics-guided diffusion that jointly forecasts drivers + imagery — the WRF/CAMx-emulation idea applied to satellite data." },
        { title: "CAFOSat: A Strongly Annotated Dataset for Infrastructure-Aware CAFO Mapping from High-Res Imagery", why: "Detecting man-made facilities in high-res satellite — the closest analog to brick-kiln mapping / SentinelKilnDB." },
        { title: "Covariance Meets Context: Transformer-Based SAR Covariance Prediction Across Frequencies and Time", why: "SAR-specific temporal/frequency modeling — for the SAR student project." },
        { title: "Pretrain Where? How Pretraining Data Diversity Impacts Geospatial Foundation Model Performance", why: "Practical pretraining-data guidance — directly useful before training kiln detectors." },
        { title: "Location Is All You Need: Continuous Spatiotemporal Neural Representations of EO Data", why: "Continuous spatio-temporal EO representations — relevant to AIRDELHI fields and sensor placement." },
        { title: "Sub-Meter Canopy Height Models from Sentinel-2 via Generative Flow Matching", why: "Fine-scale regression from coarse Sentinel-2 — super-resolution-style environmental mapping." },
        { title: "NeuCo-Bench: A Benchmark Framework for Neural Embeddings in Earth Observation", why: "Benchmark methodology for EO embeddings — comparator design for the lab's own benchmarks." }
      ] },
    { title: "CV4Science: Using Computer Vision for the Sciences", when: "Thu, PM",
      url: "https://sites.google.com/nyu.edu/computervisionforscience", tier: "must",
      tags: ["science","interpretable","discovery"],
      why: "Co-organized by Utkarsh Mall (author of DiSciPLE). The whole-lab ethos: CV as a scientific instrument. Best venue to meet the interpretable-scientific-program crowd. (Poster papers via rolling review — not public yet; key invited talks below.)",
      papers: [
        { kind: "talk", title: "Are remote sensing foundation models ready for science applications? — Hannah Kerner (ASU)", why: "Asks exactly whether RS foundation models are usable for science — central to the lab's kiln/yield/air-quality pipelines." },
        { kind: "talk", title: "Active Measurement: Turning Computer Vision Models into Scientific Instruments — Subhransu Maji (UMass)", why: "Human-in-the-loop CV as a measurement tool — the lab's active-learning + sensing philosophy." },
        { kind: "talk", title: "From Neural Rendering to Scientific Inference: Physics-Informed NeRFs — Robert Jarolim (NASA)", why: "Physics-informed reconstruction for science — the interpretable/physics-grounded modeling direction." }
      ] },
    { title: "MORSE: Foundation & Large Vision Models in Remote Sensing (2nd)", when: "Wed, PM",
      url: "https://sites.google.com/view/cvpr-morse/", tier: "must",
      tags: ["remote-sensing","foundation-models"],
      why: "RS foundation models — candidate pretrained backbones for kiln/SAR/yield detectors." },
    { title: "MONTI: Monitoring the World through an Imperfect Lens (1st)", when: "—",
      url: "https://sites.google.com/view/monti2026/home", tier: "must",
      tags: ["monitoring","air-quality","sensing"],
      why: "Monitoring with noisy/imperfect sensors — squarely the lab's air-quality monitoring-reliability and low-cost-sensor story." },
    { title: "Agriculture-Vision: CV in Agriculture (7th + CVML Challenge)", when: "Wed, PM",
      url: "https://www.agriculture-vision.com", tier: "must",
      tags: ["agriculture","yield","PlantDoc"],
      why: "Aerial agriculture imagery + challenge — yield student work and PlantDoc fit directly." },
    { title: "TRUE-V: Trustworthy, Robust, Uncertainty-Aware & Explainable Visual Intelligence", when: "—",
      url: "https://trustworthy-ai-workshop.github.io/cvpr2026-TRUE-V/", tier: "adjacent",
      tags: ["uncertainty","conformal","trustworthy"],
      why: "Conformal-NILM and NILM-UQ belong here; good venue for the lab's calibration/UQ angle." },
    { title: "Agentic AI for Visual Media", when: "Wed, full day",
      url: "https://agentic-visual-media.github.io/", tier: "adjacent",
      tags: ["agentic","LLM-agents"],
      why: "Agentic systems — relevant to VayuChat's analytics-agent direction." },
    { title: "GRAIL-V: Grounded Retrieval & Agentic Intelligence for Vision-Language", when: "Wed, AM",
      url: "https://cvpr.thecvf.com/virtual/2026/events/workshop", tier: "adjacent",
      tags: ["agentic","RAG","VLM"],
      why: "Retrieval + agentic VLMs — the toolkit behind a more rigorous VayuChat/VayuBuddy." },
    { title: "Computer Vision in the Wild: Unified Multimodal Agents for Reasoning (5th)", when: "—",
      url: "https://computer-vision-in-the-wild.github.io/cvpr-2026", tier: "adjacent",
      tags: ["agentic","VLM"],
      why: "Open-world multimodal agents; useful framing for data-analytics agents." },
    { title: "XAI4CV: Explainable AI for Computer Vision (5th)", when: "—",
      url: "https://xai4cv-workshop.github.io/xai4cv2026/", tier: "adjacent",
      tags: ["interpretable","XAI"],
      why: "Interpretability — pairs with the DiSciPLE-style interpretable-program direction." }
  ],

  clusters: [
    {
      id: "remote-sensing",
      name: "Satellite & remote-sensing detection",
      desc: "Oriented object detection, RS foundation models, dataset integrity, counting under hard conditions.",
      labMap: ["SentinelKilnDB", "Space-to-Policy"],
      papers: [
        { tier:"must", title:"Fourier Angle Alignment for Oriented Object Detection in Remote Sensing",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Gu_Fourier_Angle_Alignment_for_Oriented_Object_Detection_in_Remote_Sensing_CVPR_2026_paper.html",
          maps:["SentinelKilnDB"], why:"The exact OBB angle-regression problem SentinelKilnDB benchmarks; new angle encoding to borrow." },
        { tier:"must", title:"Partial Weakly-Supervised Oriented Object Detection",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Liu_Partial_Weakly-Supervised_Oriented_Object_Detection_CVPR_2026_paper.html",
          maps:["SentinelKilnDB"], why:"Cut kiln-annotation cost with partial/weak oriented labels." },
        { tier:"must", title:"Data Leakage Detection and De-duplication in Large-Scale Geospatial Image Datasets",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Adimoolam_Data_Leakage_Detection_and_De-duplication_in_Large_Scale_Geospatial_Image_CVPR_2026_paper.html",
          maps:["SentinelKilnDB"], why:"Train/test-integrity checklist for the next dataset release — geospatial-specific leakage." },
        { tier:"adjacent", title:"Rotation Invariant and Symmetry Aware Pixel Difference Network for RS Object Detection",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Zhan_Rotation_Invariant_and_Symmetry_Aware_Pixel_Difference_Network_for_Remote_CVPR_2026_paper.html",
          maps:["SentinelKilnDB"], why:"Kilns are near-symmetric; rotation-invariant backbone." },
        { tier:"adjacent", title:"Balanced Hierarchical Contrastive Learning with Decoupled Queries for Fine-grained RS Detection",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Chen_Balanced_Hierarchical_Contrastive_Learning_with_Decoupled_Queries_for_Fine-grained_Object_CVPR_2026_paper.html",
          maps:["SentinelKilnDB"], why:"Fine-grained kiln-type separation (FCBTK vs zigzag)." },
        { tier:"adjacent", title:"VLM4RSDet: Collaborative Optimization with VLM for RS Object Detection",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Shi_VLM4RSDet_Collaborative_Optimization_with_Vision-Language_Model_for_Enhancing_Remote_Sensing_CVPR_2026_paper.html",
          maps:["SentinelKilnDB"], why:"Language-guided detection if kiln detection goes open-vocabulary." },
        { tier:"adjacent", title:"See What We Cannot See: Geo-guided Object Counting under Adverse Earth Observation",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Wang_See_What_We_Cannot_See_A_Geo-guided_Reasoning_Benchmark_for_CVPR_2026_paper.html",
          maps:["Space-to-Policy"], why:"Counting kilns under haze/cloud; benchmark of failure conditions." },
        { tier:"adjacent", title:"ZoomEarth: Active Perception for Ultra-High-Resolution Geospatial VL Tasks",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Liu_ZoomEarth_Active_Perception_for_Ultra-High-Resolution_Geospatial_Vision-Language_Tasks_CVPR_2026_paper.html",
          maps:["Space-to-Policy"], why:"Search strategy for tiny objects in huge tiles — kiln search at national scale." },
        { tier:"adjacent", title:"ChangeBridge: Spatiotemporal Image Generation with Multimodal Controls for Remote Sensing",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Zhao_ChangeBridge_Spatiotemporal_Image_Generation_with_Multimodal_Controls_for_Remote_Senisng_CVPR_2026_paper.html",
          maps:["Space-to-Policy"], why:"Change detection over time = compliance monitoring (new vs demolished kilns)." },
        { tier:"adjacent", title:"OlmoEarth: Stable Latent Image Modeling for Multimodal Earth Observation",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Herzog_OlmoEarth_Stable_Latent_Image_Modeling_for_Multimodal_Earth_Observation_CVPR_2026_paper.html",
          maps:["SentinelKilnDB"], why:"Open RS foundation model — candidate pretrained encoder." },
        { tier:"adjacent", title:"RAMEN: Resolution-Adjustable Multimodal Encoder for Earth Observation",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Houdre_RAMEN_Resolution-Adjustable_Multimodal_Encoder_for_Earth_Observation_CVPR_2026_paper.html",
          maps:["SentinelKilnDB"], why:"Multi-resolution EO encoder — handles mixed-GSD satellite sources." },
        { tier:"adjacent", title:"NeighborMAE: Spatial-Dependency Masked Autoencoders for EO Pretraining",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Zeng_NeighborMAE_Exploiting_Spatial_Dependencies_between_Neighboring_Earth_Observation_Images_in_CVPR_2026_paper.html",
          maps:["SentinelKilnDB"], why:"Self-supervised pretraining exploiting spatial correlation across tiles." }
      ]
    },
    {
      id: "sar",
      name: "SAR imagery",
      desc: "Synthetic-aperture-radar representation learning, VLMs, optical-SAR fusion.",
      labMap: ["SentinelKilnDB", "Space-to-Policy"],
      papers: [
        { tier:"must", title:"SARMAE: Masked Autoencoder for SAR Representation Learning", student:"SAR",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Liu_SARMAE_Masked_Autoencoder_for_SAR_Representation_Learning_CVPR_2026_paper.html",
          maps:["SentinelKilnDB"], why:"SAR-specific self-supervised pretraining — backbone for SAR student work." },
        { tier:"must", title:"FUSAR-GPT: A Two-Stage Decoupled Vision-Language Model for SAR Imagery", student:"SAR",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Zhang_FUSAR-GPT_A_Spatiotemporal_Feature-Embedded_and_Two-Stage_Decoupled_Visual_Language_Model_CVPR_2026_paper.html",
          maps:["SentinelKilnDB"], why:"A VLM purpose-built for SAR — captioning/QA over radar imagery." },
        { tier:"adjacent", title:"MM-OVSeg: Multimodal Optical-SAR Fusion for Open-Vocabulary Segmentation in RS", student:"SAR",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Wei_MM-OVSeg_Multimodal_Optical-SAR_Fusion_for_Open-Vocabulary_Segmentation_in_Remote_Sensing_CVPR_2026_paper.html",
          maps:["SentinelKilnDB"], why:"Fuse cloud-penetrating SAR with optical for all-weather mapping." },
        { tier:"adjacent", title:"MOS: Mitigating the Optical-SAR Modality Gap for Cross-Modal Re-Identification", student:"SAR",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Zhao_MOS_Mitigating_Optical-SAR_Modality_Gap_for_Cross-Modal_Ship_Re-Identification_CVPR_2026_paper.html",
          maps:["SentinelKilnDB"], why:"Bridging the optical↔SAR domain gap — useful when only one modality is labeled." }
      ]
    },
    {
      id: "yield",
      name: "Crop yield & agriculture",
      desc: "Satellite crop-yield prediction, phenology, fine-grained plant recognition.",
      labMap: ["PlantDoc"],
      papers: [
        { tier:"must", title:"YieldSAT: A Multimodal Benchmark Dataset for High-Resolution Crop Yield Prediction", student:"Yield",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Miranda_YieldSAT_A_Multimodal_Benchmark_Dataset_for_High-Resolution_Crop_Yield_Prediction_CVPR_2026_paper.html",
          maps:["PlantDoc"], why:"Satellite + agriculture benchmark — the reference dataset for yield student work." },
        { tier:"must", title:"PhenoYieldNet: Learning Crop-Aware Phenological Responses for Multi-Crop Yield Prediction", student:"Yield",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Luo_PhenoYieldNet_Learning_Crop-Aware_Phenological_Responses_for_Multi-Crop_Yield_Prediction_CVPR_2026_paper.html",
          maps:["PlantDoc"], why:"Temporal crop-phenology modeling — strong baseline/architecture for yield." },
        { tier:"adjacent", title:"Plant Taxonomy Meets Plant Counting: Fine-Grained Taxonomic Counting Dataset", student:"Yield",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Xu_Plant_Taxonomy_Meets_Plant_Counting_A_Fine-Grained_Taxonomic_Dataset_for_CVPR_2026_paper.html",
          maps:["PlantDoc"], why:"Fine-grained plant recognition + counting — relevant to plant-health datasets." }
      ]
    },
    {
      id: "atmospheric",
      name: "Atmospheric / weather / climate modeling (WRF, WRF-CAMx)",
      desc: "ML emulators, surrogates, downscalers and neural operators for physics-based geophysical models — the modern ML counterpart to WRF (meteorology) and CAMx (chemical transport).",
      labMap: ["AIRDELHI", "DeepGP-AQ", "DRL-HouseControl"],
      papers: [
        { tier:"must", title:"PhyOceanCast: Global Ocean Forecasting with Physics-Informed Diffusion",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Li_PhyOceanCast_Global_Ocean_Forecasting_with_Physics-Informed_Diffusion_CVPR_2026_paper.html",
          maps:["AIRDELHI"], why:"Physics-informed diffusion emulating a numerical geophysical model — the template for an ML WRF/CAMx surrogate." },
        { tier:"must", title:"NESTOR: A Nested MoE-based Neural Operator for Large-Scale PDE Pre-Training",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Sun_NESTOR_A_Nested_MOE-based_Neural_Operator_for_Large-Scale_PDE_Pre-Training_CVPR_2026_paper.html",
          maps:["AIRDELHI"], why:"Neural operators are the principled way to learn PDE solvers — i.e. replace/accelerate the transport equations CAMx solves." },
        { tier:"must", title:"Probabilistic Precipitation Nowcasting with Rectified Flow Transformers",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Schusterbauer_Probabilistic_Precipitation_Nowcasting_with_Rectified_Flow_Transformers_CVPR_2026_paper.html",
          maps:["AIRDELHI"], why:"Probabilistic spatio-temporal nowcasting — same machinery for short-horizon PM nowcasting." },
        { tier:"must", title:"MeteorPred: A Meteorological Multimodal Large Model & Dataset for Severe Weather Prediction",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Tang_MeteorPred_A_Meteorological_Multimodal_Large_Model_and_Dataset_for_Severe_CVPR_2026_paper.html",
          maps:["AIRDELHI"], why:"A multimodal meteorology foundation model + dataset; meteorology is the input layer of WRF-CAMx." },
        { tier:"adjacent", title:"STCast: Adaptive Boundary Alignment for Global and Regional Weather Forecasting",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Chen_STCast_Adaptive_Boundary_Alignment_for_Global_and_Regional_Weather_Forecasting_CVPR_2026_paper.html",
          maps:["AIRDELHI"], why:"Global↔regional nesting — exactly WRF's nested-domain problem, learned." },
        { tier:"adjacent", title:"Spatiotemporal Pyramid Flow Matching for Climate Emulation",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Irvin_Spatiotemporal_Pyramid_Flow_Matching_for_Climate_Emulation_CVPR_2026_paper.html",
          maps:["AIRDELHI"], why:"Generative climate-field emulation across scales." },
        { tier:"adjacent", title:"Physics-Consistent Diffusion for Efficient Fluid Super-Resolution",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Li_Physics-Consistent_Diffusion_for_Efficient_Fluid_Super-Resolution_via_Multiscale_Residual_Correction_CVPR_2026_paper.html",
          maps:["AIRDELHI"], why:"Physics-consistent downscaling of fluid fields — dynamical-downscaling analog for met/AQ grids." },
        { tier:"adjacent", title:"AviaSafe: A Physics-Informed Data-Driven Model for Safety-Critical Cloud Forecasts",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Zhu_AviaSafe_A_Physics-Informed_Data-Driven_Model_for_Aviation_Safety-Critical_Cloud_Forecasts_CVPR_2026_paper.html",
          maps:["AIRDELHI"], why:"Operational physics-informed forecasting pipeline; design pattern for AQ early-warning." },
        { tier:"adjacent", title:"Spatial-Spectral Residuals Informed Diffusion Neural Operator for Pan-sharpening",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Huang_Spatial-Spectral_Residuals_Informed_Diffusion_Neural_Operator_for_Pan-sharpening_CVPR_2026_paper.html",
          maps:["AIRDELHI"], why:"Neural-operator + spectral residuals — reusable for multi-resolution AQ/met field fusion." }
      ]
    },
    {
      id: "air-quality",
      name: "Air quality, spatio-temporal inference & sensor placement",
      desc: "Air-quality forecasting, spatio-temporal field modeling, scalable Gaussian processes.",
      labMap: ["AIRDELHI", "DeepGP-AQ", "AQ-SensorPlacement"],
      papers: [
        { tier:"must", title:"Real-Time Long-Horizon Air Quality Forecasting via Group-Relative Policy Optimization",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Kang_Real-Time_Long_Horizon_Air_Quality_Forecasting_via_Group-Relative_Policy_Optimization_CVPR_2026_paper.html",
          maps:["AIRDELHI","DeepGP-AQ"], why:"Air-quality forecasting at CVPR — must compare against the lab's GP/DL approaches." },
        { tier:"adjacent", title:"GP-4DGS: Probabilistic 4D Gaussian Splatting via Variational Gaussian Processes",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Kim_GP-4DGS_Probabilistic_4D_Gaussian_Splatting_from_Monocular_Video_via_Variational_CVPR_2026_paper.html",
          maps:["DeepGP-AQ","AQ-SensorPlacement"], why:"Modern scalable variational GP inside a vision pipeline — cross-pollinates with Deep-GP-for-AQ and sensor-placement objectives." }
      ]
    },
    {
      id: "thermal",
      name: "Thermal imaging for health sensing",
      desc: "Mobile thermal image quality, IR super-resolution, thermal evaluation/benchmarks, RGB↔thermal.",
      labMap: ["JoulesEye", "ThermEval", "SpiroMask"],
      papers: [
        { tier:"must", title:"3M-TI: High-Quality Mobile Thermal Imaging via Calibration-free Multi-Camera Cross-Modal Diffusion",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Chen_3M-TI_High-Quality_Mobile_Thermal_Imaging_via_Calibration-free_Multi-Camera_Cross-Modal_Diffusion_CVPR_2026_paper.html",
          maps:["JoulesEye"], why:"Improving low-cost mobile thermal image quality — squarely JoulesEye's sensing setup." },
        { tier:"must", title:"IF-Bench: Benchmarking and Enhancing MLLMs for Infrared Images",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Zhang_IF-Bench_Benchmarking_and_Enhancing_MLLMs_for_Infrared_Images_with_Generative_CVPR_2026_paper.html",
          maps:["ThermEval"], why:"A thermal/IR benchmark — methodology template and comparison point for ThermEval." },
        { tier:"must", title:"Bridging Human Evaluation to Infrared and Visible Image Fusion",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Liu_Bridging_Human_Evaluation_to_Infrared_and_Visible_Image_Fusion_CVPR_2026_paper.html",
          maps:["ThermEval"], why:"How to build human-grounded eval for IR — directly informs ThermEval's protocol." },
        { tier:"adjacent", title:"Toward Real-world Infrared Image Super-Resolution (framework + dataset)",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Zou_Toward_Real-world_Infrared_Image_Super-Resolution_A_Unified_Autoregressive_Framework_and_CVPR_2026_paper.html",
          maps:["JoulesEye"], why:"Upscale cheap low-res thermal sensors used in JoulesEye." },
        { tier:"adjacent", title:"TherA: Thermal-Aware VL Prompting for Controllable RGB-to-Thermal Translation",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Lee_TherA_Thermal-Aware_Visual-Language_Prompting_for_Controllable_RGB-to-Thermal_Infrared_Translation_CVPR_2026_paper.html",
          maps:["JoulesEye","ThermEval"], why:"Synthesize thermal training data from RGB — augmentation for thermal health models." },
        { tier:"adjacent", title:"Dual Band Thermal Videography: Separating Reflection and Emission Near Ambient",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Narayanan_Dual_Band_Thermal_Videography_Separating_Time-Varying_Reflection_and_Emission_Near_CVPR_2026_paper.html",
          maps:["JoulesEye"], why:"Physics of the thermal signal at body temperature — relevant to isolating the respiration heat trace." },
        { tier:"adjacent", title:"VT-Intrinsic: Physics-Based Reflectance/Shading from a Visible-Thermal Pair",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Yuan_VT-Intrinsic_Physics-Based_Decomposition_of_Reflectance_and_Shading_using_a_Single_CVPR_2026_paper.html",
          maps:["JoulesEye"], why:"RGB+thermal intrinsic decomposition." }
      ]
    },
    {
      id: "thermal-detection",
      name: "Low-res thermal small-object & landmark detection",
      desc: "The JoulesEye/ApneaEye pain point: localizing a tiny region (the nostril) in low-resolution, low-SNR thermal video to track breathing. Infrared small-target detection, thermal video super-resolution, and temporally-consistent keypoint detection under degradation.",
      labMap: ["JoulesEye", "ApneaEye"],
      papers: [
        { tier:"must", title:"Seeing Through the Noise: Improving Infrared Small Target Detection and Segmentation from a Noise-Suppression Perspective",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Yuan_Seeing_Through_the_Noise_Improving_Infrared_Small_Target_Detection_and_CVPR_2026_paper.html",
          maps:["ApneaEye","JoulesEye"], why:"Detects + segments tiny targets in noisy/low-SNR infrared — directly the nostril-region problem in low-res thermal." },
        { tier:"must", title:"Target-Aware Invertible Encoder with Reconstruction Guidance for Infrared Small Target Detection",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Yan_Target-Aware_Invertible_Encoder_with_Reconstruction_Guidance_for_Infrared_Small_Target_CVPR_2026_paper.html",
          maps:["ApneaEye","JoulesEye"], why:"Reconstruction-guided encoder that preserves tiny IR structures — keeps the nostril signal from being smoothed away." },
        { tier:"must", title:"Thermal Diffusion Matters: Infrared Spatio-Temporal Video Super-Resolution through Heat-Conduction Priors",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Zhou_Thermal_Diffusion_Matters_Infrared_Spatial-Temporal_Video_Super-Resolution_through_Heat_Conduction_CVPR_2026_paper.html",
          maps:["ApneaEye","JoulesEye"], why:"Physics-grounded thermal VIDEO super-resolution — upscale low-res breathing video so nostrils become resolvable, then detect." },
        { tier:"adjacent", title:"CHAL: Causal-guided Hierarchical Anomaly-aware Learning for Moving Infrared Small Target Detection",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Duan_CHAL_Causal-guided_Hierarchical_Anomaly-aware_Learning_for_Moving_Infrared_Small_Target_CVPR_2026_paper.html",
          maps:["ApneaEye"], why:"Moving small-target detection in IR video — respiration is a moving thermal signal across frames." },
        { tier:"adjacent", title:"DyFCLT: Dynamic Frequency-Decoupled Cross-Modal Learning Transformer for Multimodal Tiny Object Detection",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Li_DyFCLT_Dynamic_Frequency-Decoupled_Cross-Modal_Learning_Transformer_for_Multimodal_Tiny_Object_CVPR_2026_paper.html",
          maps:["JoulesEye","ApneaEye"], why:"RGB-thermal tiny-object detection — fuse the higher-res RGB view to localize the nostril when thermal alone is too coarse." },
        { tier:"adjacent", title:"From Pairs to Sequences: Track-Aware Policy Gradients for Keypoint Detection",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Liu_From_Pairs_to_Sequences_Track-Aware_Policy_Gradients_for_Keypoint_Detection_CVPR_2026_paper.html",
          maps:["ApneaEye"], why:"Temporally-consistent keypoint detection — track the nostril keypoint stably across a breathing sequence." },
        { tier:"adjacent", title:"BDNet: Bio-Inspired Dual-Backbone Small Object Detection Network",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Guan_BDNetBio-Inspired_Dual-Backbone_Small_Object_Detection_Network_CVPR_2026_paper.html",
          maps:["JoulesEye"], why:"General small-object detector architecture — backbone idea for low-res facial-region detection." },
        { tier:"adjacent", title:"Small Object, Great Challenge: A Benchmark for Small Object Visual Grounding",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Jia_Small_Object_Great_Challenge_A_Benchmark_for_Small_Object_Visual_CVPR_2026_paper.html",
          maps:["ApneaEye"], why:"Benchmark + grounding for very small objects — evaluation methodology for nostril-scale targets." }
      ]
    },
    {
      id: "physio",
      name: "Camera-based / remote physiological sensing",
      desc: "Contactless vitals and physiological signals from video.",
      labMap: ["JoulesEye", "SpiroMask", "SpiroActive"],
      papers: [
        { tier:"must", title:"FLOW: Optimal Transport-Driven Feature Warping for Generalized Remote Physiological Measurement",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Zhao_FLOW_Optimal_Transport-Driven_Feature_Warping_for_Generalized_Remote_Physiological_Measurement_CVPR_2026_paper.html",
          maps:["JoulesEye"], why:"Contactless vitals from video — the camera-based analog of the lab's contactless respiration sensing." },
        { tier:"adjacent", title:"rPPG-VQA: Video Quality Assessment for Unsupervised rPPG Training",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Dai_rPPG-VQA_A_Video_Quality_Assessment_Framework_for_Unsupervised_rPPG_Training_CVPR_2026_paper.html",
          maps:["JoulesEye"], why:"Quality-gating noisy physiological video — useful for in-the-wild exercise capture." },
        { tier:"adjacent", title:"HUMAPS-4D: Multimodal Dataset for Human Motion Analysis with Physiological Signals",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Dabrowski_HUMAPS-4D_A_Multimodal_Dataset_for_HUman_Motion_Analysis_with_Physiological_CVPR_2026_paper.html",
          maps:["JoulesEye"], why:"Joint motion + physiology dataset — comparator for JoulesEye-during-exercise." }
      ]
    },
    {
      id: "active-learning",
      name: "Active learning / label-efficient acquisition",
      desc: "Acquisition strategies, pool curation, open-set and federated AL.",
      labMap: ["NILM-AL", "SpiroActive"],
      papers: [
        { tier:"must", title:"Portable Active Learning for Object Detection",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Sharma_Portable_Active_Learning_for_Object_Detection_CVPR_2026_paper.html",
          maps:["NILM-AL","SentinelKilnDB"], why:"AL for detection transfers directly to reducing kiln-annotation effort." },
        { tier:"must", title:"Similarity-as-Evidence: Calibrating Overconfident VLMs for Label-Efficient Active Learning",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Xie_Similarity-as-Evidence_Calibrating_Overconfident_VLMs_for_Interpretable_and_Label-Efficient_Medical_Active_CVPR_2026_paper.html",
          maps:["SpiroActive","Conformal-NILM"], why:"Fuses AL + calibration — i.e. SpiroActive ∪ Conformal-NILM in one paper." },
        { tier:"adjacent", title:"Cleaning the Pool: Progressive Filtering of Unlabeled Pools in Deep AL",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Huseljic_Cleaning_the_Pool_Progressive_Filtering_of_Unlabeled_Pools_in_Deep_CVPR_2026_paper.html",
          maps:["NILM-AL"], why:"Pool curation — a recurring NILM-AL pain point." },
        { tier:"adjacent", title:"Revisiting Unknowns: Towards Effective and Efficient Open-Set Active Learning",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Zong_Revisiting_Unknowns_Towards_Effective_and_Efficient_Open-Set_Active_Learning_CVPR_2026_paper.html",
          maps:["NILM-AL"], why:"AL when the unlabeled pool contains unknown classes." },
        { tier:"adjacent", title:"Label What Matters: Modality-Balanced, Difficulty-Aware Multimodal Active Learning",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Zeng_Label_What_Matters_Modality-Balanced_and_Difficulty-Aware_Multimodal_Active_Learning_CVPR_2026_paper.html",
          maps:["SpiroActive"], why:"AL across modalities — relevant to multi-sensor health data." },
        { tier:"adjacent", title:"Federated Active Learning Under Extreme Non-IID & Class Imbalance",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Zong_Federated_Active_Learning_Under_Extreme_Non-IID_and_Global_Class_Imbalance_CVPR_2026_paper.html",
          maps:["NILM-AL"], why:"Distributed AL — maps to multi-home NILM / multi-city sensing." }
      ]
    },
    {
      id: "uncertainty",
      name: "Uncertainty quantification & conformal prediction",
      desc: "Distribution-free guarantees, conformal prediction, calibration under shift.",
      labMap: ["Conformal-NILM", "NILM-UQ"],
      papers: [
        { tier:"must", title:"Spectral Conformal Risk Control: Distribution-Free Tail Guarantees via Bayesian Quadrature",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Esfeh_Spectral_Conformal_Risk_Control_Distribution-Free_Tail_Guarantees_via_Bayesian_Quadrature_CVPR_2026_paper.html",
          maps:["Conformal-NILM"], why:"Distribution-free guarantees — the lab's exact framing for NILM UQ." },
        { tier:"must", title:"Semi-Supervised Conformal Prediction with Unlabeled Nonconformity Score",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Zhou_Semi-Supervised_Conformal_Prediction_With_Unlabeled_Nonconformity_Score_CVPR_2026_paper.html",
          maps:["Conformal-NILM","NILM-AL"], why:"Conformal with few labels — pairs naturally with the lab's AL work." },
        { tier:"adjacent", title:"Query2Uncertainty: Robust UQ & Calibration for Detection under Distribution Shift",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Beemelmanns_Query2Uncertainty_Robust_Uncertainty_Quantification_and_Calibration_for_3D_Object_Detection_CVPR_2026_paper.html",
          maps:["NILM-UQ"], why:"UQ under shift — mirrors cross-region NILM/AQ deployment." },
        { tier:"adjacent", title:"Multimodal Learning on Low-Quality Data with Conformal Predictive Self-Calibration",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Jiang_Multimodal_Learning_on_Low-Quality_Data_with_Conformal_Predictive_Self-Calibration_CVPR_2026_paper.html",
          maps:["Conformal-NILM"], why:"Conformal under noisy inputs — common in low-cost-sensor data." },
        { tier:"adjacent", title:"Conditional Factuality Controlled LLMs via Conformal Sampling",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Ye_Conditional_Factuality_Controlled_LLMs_with_Generalization_Certificates_via_Conformal_Sampling_CVPR_2026_paper.html",
          maps:["Conformal-NILM","VayuChat/VayuBuddy"], why:"Conformal guarantees on LLM outputs — rigor for VayuChat/VayuBuddy answers." },
        { tier:"adjacent", title:"LATA: Conformal Uncertainty in Medical VLMs",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Bozorgtabar_LATA_Laplacian-Assisted_Transductive_Adaptation_for_Conformal_Uncertainty_in_Medical_VLMs_CVPR_2026_paper.html",
          maps:["Conformal-NILM"], why:"Applied conformal-on-VLM recipe." }
      ]
    },
    {
      id: "data-llm",
      name: "LLM/VLM for data analytics",
      desc: "Chart-to-code, table reasoning, chart QA — the machinery behind VayuChat.",
      labMap: ["VayuChat/VayuBuddy"],
      papers: [
        { tier:"must", title:"MM-ReCoder: Chart-to-Code Generation with RL and Self-Correction",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Tang_MM-ReCoder_Advancing_Chart-to-Code_Generation_with_Reinforcement_Learning_and_Self-Correction_CVPR_2026_paper.html",
          maps:["VayuChat/VayuBuddy"], why:"Exactly VayuChat's NL→plotting-code loop, with self-correction." },
        { tier:"adjacent", title:"TableMix: Multimodal Table Reasoning in MLLMs (Data-Centric)",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Liu_TableMix_Enhancing_Multimodal_Table_Reasoning_in_MLLMs_from_a_Data-Centric_CVPR_2026_paper.html",
          maps:["VayuChat/VayuBuddy"], why:"Reasoning over tabular data = VayuChat's core." },
        { tier:"adjacent", title:"Twin-T & TwintVQA: VLM + Benchmark for Chart and Table Tasks",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Bao_Twin-T__TwintVQA_A_Reliable_Structure-Detail_Separating_VLM_and_a_CVPR_2026_paper.html",
          maps:["VayuChat/VayuBuddy"], why:"Eval design for chart/table QA — comparator for VayuBench." },
        { tier:"adjacent", title:"ChartR: Evaluating Reasoning Accuracy and Robustness in Chart QA",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Chen_ChartR_Evaluating_Reasoning_Accuracy_and_Robustness_in_Chart_Question_Answering_CVPR_2026_paper.html",
          maps:["VayuChat/VayuBuddy"], why:"Robustness evaluation for chart understanding." },
        { tier:"adjacent", title:"MultiModalPFN: Prior-Data Fitted Networks for Multimodal Tabular Learning",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Kim_MultiModalPFN_Extending_Prior-Data_Fitted_Networks_for_Multimodal_Tabular_Learning_CVPR_2026_paper.html",
          maps:["VayuChat/VayuBuddy","AIRDELHI"], why:"In-context tabular prediction — relevant to small-data air-quality tables." }
      ]
    },
    {
      id: "agentic",
      name: "Agentic & tool-using systems",
      desc: "Tool-integrated reasoning, self-evolving agents, multi-agent research helpers.",
      labMap: ["VayuChat/VayuBuddy"],
      papers: [
        { tier:"must", title:"Scaling Agentic Reinforcement Learning for Tool-Integrated Reasoning in VLMs",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Lu_Scaling_Agentic_Reinforcement_Learning_for_Tool-Integrated_Reasoning_in_VLMs_CVPR_2026_paper.html",
          maps:["VayuChat/VayuBuddy"], why:"Tool-using VLMs trained with RL — the engine for a more capable VayuChat agent." },
        { tier:"adjacent", title:"VisPlay: Self-Evolving Vision-Language Models",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/He_VisPlay_Self-Evolving_Vision-Language_Models_CVPR_2026_paper.html",
          maps:["VayuChat/VayuBuddy"], why:"Self-improvement without new labels — in the DiSciPLE/self-evolving spirit." },
        { tier:"adjacent", title:"SpaceTools: Tool-Augmented Spatial Reasoning via Double Interactive RL",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Chen_SpaceTools_Tool-Augmented_Spatial_Reasoning_via_Double_Interactive_RL_CVPR_2026_paper.html",
          maps:["VayuChat/VayuBuddy"], why:"Tool-augmented spatial reasoning — geospatial-query agents." },
        { tier:"adjacent", title:"EvoGraph-R1: Self-Evolving Multimodal Knowledge Hypergraphs for Agentic Retrieval",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Lin_EvoGraph-R1_Self-Evolving_Multimodal_Knowledge_Hypergraphs_for_Agentic_Retrieval_CVPR_2026_paper.html",
          maps:["VayuChat/VayuBuddy"], why:"Agentic retrieval over an evolving knowledge graph — grounding for data Q&A." },
        { tier:"adjacent", title:"ARM-Thinker: Reinforcing Multimodal Reward Models with Agentic Tool Use and Visual Reasoning",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Ding_ARM-Thinker_Reinforcing_Multimodal_Generative_Reward_Models_with_Agentic_Tool_Use_CVPR_2026_paper.html",
          maps:["VayuChat/VayuBuddy"], why:"Reward models for agentic tool use — how to score multi-step analytics answers." },
        { tier:"adjacent", title:"Consensus Entropy: Multi-VLM Agreement for Self-Verifying & Self-Improving OCR",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Zhang_Consensus_Entropy_Harnessing_Multi-VLM_Agreement_for_Self-Verifying_and_Self-Improving_OCR_CVPR_2026_paper.html",
          maps:["VayuChat/VayuBuddy"], why:"Self-verification via model agreement — a cheap reliability signal for agent outputs." },
        { tier:"adjacent", title:"Paper2Figure: Multi-Agent System for Figure Generation for Research Papers",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Han_Paper2Figure_A_Multi-Agent_Collaborative_System_for_Figure_Generation_Towards_Academic_CVPR_2026_paper.html",
          maps:[], why:"Lab-productivity tool — auto-drafting paper figures." },
        { tier:"adjacent", title:"NERFIFY: A Multi-Agent Framework for Turning NeRF Papers into Code",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Jain_NERFIFY_A_Multi-Agent_Framework_for_Turning_NeRF_Papers_into_Code_CVPR_2026_paper.html",
          maps:[], why:"Paper→code agents — interesting for reproducibility-focused students." }
      ]
    },
    {
      id: "science-programs",
      name: "Scientific discovery & interpretable programs (DiSciPLE-like)",
      desc: "Interpretable-by-design models, neurosymbolic reasoning, concept discovery, causal discovery. " +
            "Inspired by DiSciPLE (Mall et al., CVPR 2025): LLM-guided evolutionary synthesis of interpretable Python programs for scientific visual discovery — see also the CV4Science workshop.",
      labMap: ["AQ-SensorPlacement", "Space-to-Policy"],
      papers: [
        { tier:"must", title:"A Polynomial Chaos Framework for Causal Discovery in Nonlinear Uncertain Systems",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Cao_A_Polynomial_Chaos_Framework_for_Causal_Discovery_in_Nonlinear_Uncertain_CVPR_2026_paper.html",
          maps:["AQ-SensorPlacement"], why:"Causal discovery with uncertainty — the interpretable-science direction DiSciPLE champions." },
        { tier:"adjacent", title:"Cross-Domain Demo-to-Code via Neurosymbolic Counterfactual Reasoning",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Kim_Cross-Domain_Demo-to-Code_via_Neurosymbolic_Counterfactual_Reasoning_CVPR_2026_paper.html",
          maps:[], why:"Program induction with neurosymbolic reasoning — closest in spirit to DiSciPLE's program synthesis." },
        { tier:"adjacent", title:"Interpretable and Steerable Concept Bottleneck Sparse Autoencoders",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Kulkarni_Interpretable_and_Steerable_Concept_Bottleneck_Sparse_Autoencoders_CVPR_2026_paper.html",
          maps:[], why:"Interpretable-by-design concept models — same goal as DiSciPLE, different mechanism." },
        { tier:"adjacent", title:"Hierarchical Concept Embedding & Pursuit for Interpretable Image Classification",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Nguyen_Hierarchical_Concept_Embedding__Pursuit_for_Interpretable_Image_Classification_CVPR_2026_paper.html",
          maps:[], why:"Concept-based interpretability for classification." },
        { tier:"adjacent", title:"Select, Hypothesize and Verify: Towards Verified Neuron Concept Interpretation",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Ji_Select_Hypothesize_and_Verify_Towards_Verified_Neuron_Concept_Interpretation_CVPR_2026_paper.html",
          maps:[], why:"Hypothesis-and-verify loop for interpretation — methodologically DiSciPLE-adjacent." },
        { tier:"adjacent", title:"SCIEval: Faithfulness of Scientific Image Generation & Interpretation with LMMs",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Ye_SCIEval_Evaluating_and_Benchmarking_the_Faithfulness_of_Scientific_Image_Generation_CVPR_2026_paper.html",
          maps:[], why:"Benchmarking scientific faithfulness of LMMs — eval lens for science applications." },
        { tier:"adjacent", title:"SciEducator: Scientific Video Understanding via Deming-Cycle Multi-Agent System",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Xu_SciEducator_Scientific_Video_Understanding_and_Educating_via_Deming-Cycle_Multi-Agent_System_CVPR_2026_paper.html",
          maps:[], why:"Multi-agent system aimed at science education/understanding." }
      ]
    },
    {
      id: "apparel",
      name: "Generative apparel (low priority)",
      desc: "Virtual try-on / fashion editing — a one-off lab interest (Vastr-GAN, 2022).",
      labMap: ["Vastr-GAN"],
      papers: [
        { tier:"adjacent", title:"FEAT: Fashion Editing and Try-On from Any Design",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Kwon_FEAT_Fashion_Editing_and_Try-On_from_Any_Design_CVPR_2026_paper.html",
          maps:["Vastr-GAN"], why:"Modern fashion editing + try-on; successor tech to Vastr-GAN." },
        { tier:"adjacent", title:"MV-Fashion: Virtual Try-On + Size Estimation from Multi-View Paired Data",
          url:"https://openaccess.thecvf.com/content/CVPR2026/html/Laczko_MV-Fashion_Towards_Enabling_Virtual_Try-On_and_Size_Estimation_with_Multi-View_CVPR_2026_paper.html",
          maps:["Vastr-GAN"], why:"Multi-view try-on with size estimation." }
      ]
    }
  ]
};
